### ISSUE TITLE
ImportError: cannot import name 'get_loss_mvp'

### ISSUE THREAD

**Issue by yltqy** [EasyRy/CRA-PCN#1]
Traceback (most recent call last):
  File "train_pcn.py", line 18, in <module>
    from manager import Manager
  File "/hy-tmp/CRA-PCN-main/CRA-PCN-main/manager.py", line 27, in <module>
    from utils.loss_utils_clamp import get_loss_clamp, get_loss_mvp
ImportError: cannot import name 'get_loss_mvp'

**Comment by EasyRy** [comment]
Sorry. We have fixed the problem in **manager.py**. Please replace the original file with the latest one.
