### ISSUE TITLE
您好，我在推理的时候遇到了一个参数不匹配的问题，万分感谢

### ISSUE THREAD

**Issue by sHicg1997** [EasyRy/CRA-PCN#15]
Traceback (most recent call last):
  File "/data/teeth_code/CRA-PCN/infer.py", line 38, in <module>
    model.load_state_dict(checkpoint['model'])
  File "/home/scg/.conda/envs/mmrota/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.decoder.ub2.deconv.ps.weight: copying a param with shape torch.Size([32, 128, 4]) from checkpoint, the shape in current model is torch.Size([32, 128, 8]).

**Comment by EasyRy** [comment]
你好。看起来似乎是用了PCN的权重，而model是shapenet的
